# version: '3'
# services:
#   mongo:
#     image: mongo:latest
#     container_name: mongovolume
#     ports:
#       - "27019:27017"
#     volumes:
#       - mongodata:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=rifki
#       - MONGO_INITDB_ROOT_PASSWORD=rifki

# volumes:
#   mongodata:

# Backup
version: '3.8' # Atur versi sesuai kebutuhan Anda
services:
  nginxbackup:
    image: nginx:latest
    container_name: nginxbackup
    volumes:
      - /c/Users/asus/OneDrive/Desktop/learn-docker/backup:/backup:rw
      - mongodata:/data

volumes:
  mongodata:
